---

- name: Ensure APT usage dependencies are installed
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - gnupg
    state: present
    update_cache: true

- name: Ensure Docker APT Key is installed and trusted
  apt_key:
    url: "https://download.docker.com/linux/{{ ansible_distribution|lower }}/gpg"
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present

- name: Ensure Docker repository is enabled
  apt_repository:
    repo: "deb [arch={{ system_arch }}] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    update_cache: true

- name: Ensure Docker is installed
  apt:
    name:
      - "docker"
      - "docker.io"
      - "python{{'3' if ansible_python.version.major == 3 else ''}}-docker"
    state: latest
